version: "3.8"
services:
  postgres_main:
    image: "postgres"
    container_name: "postgres_main"
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ALLOW_IP_RANGE: "0.0.0.0/0"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  postgres_test:
    image: "postgres"
    container_name: "postgres_test"
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ALLOW_IP_RANGE: "0.0.0.0/0"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  redis_test:
    image: redis:latest
    restart: always
    container_name: redis_test
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=your_password_here
    volumes:
      - redis_data:/data

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=your_password_here
    volumes:
      - redis_data:/data

volumes:
  redis_data:
